# https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/conda_build_config.yaml

llvm_version:
  - 17
  - 18
  - 19
  - 20
  - 21

c_stdlib_version:  # [linux]
  - '2.17'         # [linux]
  - '2.17'         # [linux]
  - '2.17'         # [linux]

cuda_compiler_version:         # [linux or win]
  - None                       # [linux or win]
  - '12.6'                     # [linux or win]
  - '12.9'                     # [linux or win]

cuda_compiler_version_min:     # [linux or win]
  - None                       # [linux or win]
  - '12.6'                     # [linux or win]
  - '12.9'                     # [linux or win]

c_compiler_version:            # [linux]
  - '14'                       # [linux]
  - '13'                       # [linux]
  - '14'                       # [linux]

cxx_compiler_version:          # [linux]
  - '14'                       # [linux]
  - '13'                       # [linux]
  - '14'                       # [linux]

fortran_compiler_version:      # [linux]
  - '14'                       # [linux]
  - '13'                       # [linux]
  - '14'                       # [linux]
