{% set name = "drjit-cpp" %}
{% set version = "1.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # drjit
  - url: https://github.com/mitsuba-renderer/drjit/archive/v{{ version }}.tar.gz
    sha256: 03dfe742647ad864bb3426eef7c4704206d6ceaa2b9a403ae63e4e65fa873b77
    patches:
      - patches/drjit/0001-Use-system-libraries.patch
      - patches/drjit/0002-Fix-install-destination-paths.patch
      - patches/drjit/0003-Make-directory-before-creating-files.patch
      - patches/drjit/0004-Fix-scatter-for-raw-pointer-target.patch

  # drjit-core
  - url: https://github.com/mitsuba-renderer/drjit-core/archive/c2c23f889b328c2b15017097b12cec838057fe63.zip
    sha256: ec2b67925d374a07b809ea4f7b8d89bb430020b106f0c901cbc086ca066d8b4c
    folder: ext/drjit-core
    patches:
      - patches/drjit-core/use-system-robin-map.patch
  - url: https://github.com/mitsuba-renderer/nanothread/archive/6c4dd4d425619d6a4a5dd7b7a255116411cddebb.zip
    sha256: 4160bc8acbad3250ccaa6c5ced25d9bec5e1bf1de9eea3432ac4b84aec099dcd
    folder: ext/drjit-core/ext/nanothread
  - url: https://github.com/mitsuba-renderer/cmake-defaults/archive/fd9c6552b5639232583b3e0a296c9e03c86c9c70.zip
    sha256: 545213e126f66bdb0839d6924b5989a96a283eef43f3e6c7d19d121c3ff4d595
    folder: ext/drjit-core/ext/nanothread/ext/cmake-defaults
    patches:
      - patches/drjit-core/disable-march-flags.patch  # [build_platform != target_platform]
  - url: https://github.com/Tessil/robin-map/archive/188c45569cc2a5dd768077c193830b51d33a5020.zip
    sha256: 084d7d72f2e669842cc9db1a6a31c15376500a90a3e525f63f569fca963a01b4
    folder: ext/drjit-core/ext/robin_map

  # nanobind
  - url: https://github.com/wjakob/nanobind/archive/082eab33a58d246ed408ecae59be77f694387a68.zip
    sha256: c62fa48dc6df78d42562abfa55ca8835fde4855b014b77c3c6457356430fb282
    folder: ext/nanobind
  - url: https://github.com/Tessil/robin-map/archive/188c45569cc2a5dd768077c193830b51d33a5020.zip
    sha256: 084d7d72f2e669842cc9db1a6a31c15376500a90a3e525f63f569fca963a01b4
    folder: ext/nanobind/ext/robin_map

build:
  number: 4
  skip: true  # [cuda_compiler_version == "11.8"]
  skip: true  # [cuda_compiler_version != "None" and (ppc64le or aarch64)]
  skip: true  # [cuda_compiler_version != "None" and win]
  string: cpu_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version == "None"]
  string: cuda{{ cuda_compiler_version | replace('.', '') }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
  run_exports:
    - {{ pin_subpackage('drjit-cpp', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [cuda_compiler_version != "None"]
    - {{ stdlib('c') }}
    - cmake
    - ninja  # [not win]
    - tsl_robin_map
  host:
    - cuda-version {{ cuda_compiler_version }}  # [cuda_compiler_version != "None"]
    - cuda-toolkit                              # [cuda_compiler_version != "None"]
    - llvmdev {{ llvm_version }}
  run:
    - cuda-cudart  # [cuda_compiler_version != "None"]

test:
  commands:
    - test -f $PREFIX/include/drjit/fwd.h  # [not win]
    - test -f $PREFIX/share/cmake/drjit/drjitConfig.cmake  # [not win]
    - if not exist %PREFIX%\\Library\\include\\drjit\\fwd.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\share\\cmake\\drjit\\drjitConfig.cmake exit 1  # [win]
  requires:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - cmake
    - ninja  # [unix]
  files:
    - tests/
  downstreams:
    - momentum

about:
  home: https://github.com/mitsuba-renderer/drjit
  summary: 'Dr.Jit — A Just-In-Time-Compiler for Differentiable Rendering'
  description: |
    Dr.Jit is a just-in-time (JIT) compiler for ordinary and differentiable computation. It was
    originally created as the numerical foundation of Mitsuba 3, a differentiable Monte Carlo
    renderer. However, Dr.Jit is a general-purpose tool that can also help with various other
    types of embarrassingly parallel computation.
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/mitsuba-renderer/drjit

extra:
  recipe-maintainers:
    - jeongseok-meta
