{% set name = "drjit-cpp" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/mitsuba-renderer/drjit/archive/v{{ version }}.tar.gz
    sha256: ca80fd2236dec0f94d2d05e1f002a24e59730ea40f4ba952675e68b2860fa106
    patches:
      - patches/use-system-libraries.patch
      - patches/skip-installing-jit-targets.patch
  - url: https://github.com/mitsuba-renderer/drjit-core/archive/2354093d6bffffbe8a1ce546f54edf6dd007e464.zip
    sha256: 814ca6d8d102a6fa52903271181a24ef44de58fb912d11a33e906df5dc8a043e
    folder: ext/drjit-core
    patches:
      - patches/use-system-robin-map.patch
  - url: https://github.com/mitsuba-renderer/nanothread/archive/6c4dd4d425619d6a4a5dd7b7a255116411cddebb.zip
    sha256: 4160bc8acbad3250ccaa6c5ced25d9bec5e1bf1de9eea3432ac4b84aec099dcd
    folder: ext/drjit-core/ext/nanothread
  - url: https://github.com/mitsuba-renderer/cmake-defaults/archive/fd9c6552b5639232583b3e0a296c9e03c86c9c70.zip
    sha256: 545213e126f66bdb0839d6924b5989a96a283eef43f3e6c7d19d121c3ff4d595
    folder: ext/drjit-core/ext/nanothread/ext/cmake-defaults
    patches:
      - patches/disable-march-flags.patch  # [build_platform != target_platform]

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('drjit-cpp', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - ninja  # [not win]
    - tsl_robin_map

test:
  commands:
    - test -f $PREFIX/include/drjit/fwd.h  # [not win]
    - test -f $PREFIX/share/cmake/drjit/drjitConfig.cmake  # [not win]
    - if not exist %PREFIX%\\Library\\include\\drjit\\fwd.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\share\\cmake\\drjit\\drjitConfig.cmake exit 1  # [win]
  requires:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - cmake
    - ninja  # [unix]
  files:
    - tests/
  downstreams:
    - momentum

about:
  home: https://github.com/mitsuba-renderer/drjit
  summary: 'Dr.Jit — A Just-In-Time-Compiler for Differentiable Rendering'
  description: |
    Dr.Jit is a just-in-time (JIT) compiler for ordinary and differentiable computation. It was
    originally created as the numerical foundation of Mitsuba 3, a differentiable Monte Carlo
    renderer. However, Dr.Jit is a general-purpose tool that can also help with various other
    types of embarrassingly parallel computation.
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/mitsuba-renderer/drjit

extra:
  recipe-maintainers:
    - jeongseok-meta
