{% set name = "drjit-cpp" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/mitsuba-renderer/drjit/archive/v{{ version }}.tar.gz
    sha256: 916fb7d941ed4dc5973a8ea639a107d2696ee29e990f12338d399aeade7d5490
    patches:
      - include-tuple.patch
      - disable-broken-tests.patch
      - disable-trig-test-on-apple.patch
      - test-avx512-support.patch
      - install-drjit-core-headers.patch
  - url: https://github.com/mitsuba-renderer/drjit-core/archive/a5073390f83230e42a4823966aa7df76797e11f1.zip
    sha256: 88ae053ac614cd15d0791c3e67392da2f4305385947dec4ca3b9e7ec66ccb218
    folder: ext/drjit-core
    patches:
      - use-system-robin-map.patch
  - url: https://github.com/mitsuba-renderer/nanothread/archive/8264dfc76c57a73971dfc5d8ef04e54ec0def783.zip
    sha256: ae7a56833e7824ddd4602442fa96de1b795c28d45748f308b07d5934a879e813
    folder: ext/drjit-core/ext/nanothread
  - url: https://github.com/mitsuba-renderer/cmake-defaults/archive/fd9c6552b5639232583b3e0a296c9e03c86c9c70.zip
    sha256: 545213e126f66bdb0839d6924b5989a96a283eef43f3e6c7d19d121c3ff4d595
    folder: ext/drjit-core/ext/nanothread/ext/cmake-defaults

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('drjit-cpp', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - ninja  # [not win]
    - tsl_robin_map

test:
  commands:
    - test -f $PREFIX/share/cmake/drjit/drjitConfig.cmake  # [not win]
    - if not exist %PREFIX%\\Library\\share\\cmake\\drjit\\drjitConfig.cmake exit 1  # [win]

about:
  home: https://github.com/mitsuba-renderer/drjit
  summary: 'Dr.Jit — A Just-In-Time-Compiler for Differentiable Rendering'
  description: |
    Dr.Jit is a just-in-time (JIT) compiler for ordinary and differentiable computation. It was
    originally created as the numerical foundation of Mitsuba 3, a differentiable Monte Carlo
    renderer. However, Dr.Jit is a general-purpose tool that can also help with various other
    types of embarrassingly parallel computation.
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/mitsuba-renderer/drjit

extra:
  recipe-maintainers:
    - jeongseok-meta
