schema_version: 1

context:
  name: drjit-cpp
  version: "1.4.0"
  build_number: 1

recipe:
  name: ${{ name|lower }}-split
  version: ${{ version }}

source:
  - url: https://github.com/mitsuba-renderer/drjit/archive/v${{ version }}.tar.gz
    sha256: aed2315f139f2313264638b77eb571649c28e659f1c636c834af4d0345adcdfb
    patches:
      - patches/drjit/0001-Use-system-libraries.patch
      - patches/drjit/0002-Fix-install-destination-paths.patch
      - patches/drjit/0003-Make-directory-before-creating-files.patch
      - patches/drjit/0004-Fix-scatter-for-raw-pointer-target.patch
      - patches/drjit/0005-Allow-disabling-python-stubs.patch
  - url: https://github.com/mitsuba-renderer/drjit-core/archive/c9c054928c55da09c1756366d62e60c23ceceefd.zip
    sha256: 13d9b6e2247b90f193392ef961838c0d2894eb5414b5ba3640050715fef675bf
    target_directory: ext/drjit-core
    patches:
      - patches/drjit-core/use-system-robin-map.patch
  - url: https://github.com/mitsuba-renderer/nanothread/archive/a2097209e10852962c485ee46d84d28e7a63a1a1.zip
    sha256: 5bd988bc713e516083f6e2e1c8414d5b8087c32ab5aa99a78c662acb327494b1
    target_directory: ext/drjit-core/ext/nanothread
  - url: https://github.com/mitsuba-renderer/cmake-defaults/archive/d65442956cd78772ba26ba25dc552de22566b717.zip
    sha256: 76fc76bc458bf51bd1f7d29f9088b224d93e8fbc8edf4d10767bf962fee48356
    target_directory: ext/drjit-core/ext/nanothread/ext/cmake-defaults
    patches:
      - patches/drjit-core/disable-march-flags.patch
  - url: https://github.com/Tessil/robin-map/archive/f70fd39a960385ef0a963aef00b750e4740228c0.zip
    sha256: eba811574adf28446422a4847053960eb86b06730f4e32db3d6da5d5332f38b9
    target_directory: ext/drjit-core/ext/robin_map
  - url: https://github.com/wjakob/nanobind/archive/cee9cfdc3b357699111d6d3f3fd2b022ad7f31c2.zip
    sha256: 91af61d846cbb77564190f0882994f00abf06e2b6563eb2059f63ccceb90b72d
    target_directory: ext/nanobind
  - url: https://github.com/Tessil/robin-map/archive/4ec1bf19c6a96125ea22062f38c2cf5b958e448e.zip
    sha256: 78c97483a8993866074f06b25fd288cdb7b8ebd6c61c2f0c43b0e324fd56ce10
    target_directory: ext/nanobind/ext/robin_map

build:
  number: ${{ build_number }}
  skip:
    - cuda_compiler_version != "None" and (ppc64le or aarch64)
    - cuda_compiler_version != "None" and win

outputs:
  - package:
      name: drjit-cpp
    build:
      string: ${{ "cuda" ~ (cuda_compiler_version | replace(".", "")) ~ "_llvm" ~ llvm_version ~ "_" ~ build_number if cuda_compiler_version != "None" else "cpu_llvm" ~ llvm_version ~ "_" ~ build_number }}
      skip:
        - build_mode == "python"
      script:
        file: ${{ "bld_cpp.bat" if win else "build_cpp.sh" }}
    requirements:
      build:
        - ${{ compiler("c") }}
        - ${{ compiler("cxx") }}
        - if: cuda_compiler_version != "None"
          then:
            - ${{ compiler("cuda") }}
        - ${{ stdlib("c") }}
        - cmake
        - if: unix
          then: ninja
      host:
        - if: cuda_compiler_version != "None"
          then:
            - cuda-version ==${{ cuda_compiler_version }}
            - cuda-toolkit
        - llvmdev ${{ llvm_version }}.*
      run:
        - if: cuda_compiler_version != "None"
          then: cuda-cudart
        - libllvm${{ llvm_version }}
      run_exports:
        - ${{ pin_subpackage("drjit-cpp", upper_bound="x.x") }}
    tests:
      - files:
          recipe:
            - run_test_cpp.bat
            - run_test_cpp.sh
            - tests/
        requirements:
          run:
            - ${{ compiler("c") }}
            - ${{ compiler("cxx") }}
            - ${{ stdlib("c") }}
            - cmake
            - if: unix
              then: ninja
        script:
          - if: unix
            then:
              - test -f "${PREFIX}/include/drjit-core/macros.h"
              - test -f "${PREFIX}/include/drjit/fwd.h"
              - test -f "${PREFIX}/share/cmake/drjit/drjitConfig.cmake"
              - bash run_test_cpp.sh
          - if: win
            then:
              - if not exist "%PREFIX%\\Library\\include\\drjit-core\\macros.h" exit 1
              - if not exist "%PREFIX%\\Library\\include\\drjit\\fwd.h" exit 1
              - if not exist "%PREFIX%\\Library\\share\\cmake\\drjit\\drjitConfig.cmake" exit 1
              - call run_test_cpp.bat
      - downstream: momentum

  - package:
      name: drjit
    build:
      skip:
        - build_mode == "cpp"
        - linux and not x86_64
        - win
        - match(python, "<3.10")
        - match(python, ">=3.13") and cuda_compiler_version == "13.0"
        - match(python, ">=3.14")
      script:
        file: ${{ "bld_py.bat" if win else "build_py.sh" }}
    requirements:
      build:
        - ${{ compiler("c") }}
        - ${{ compiler("cxx") }}
        - if: cuda_compiler_version != "None"
          then:
            - ${{ compiler("cuda") }}
        - ${{ stdlib("c") }}
        - cmake
        - make
        - if: unix
          then: ninja
        - if: build_platform != target_platform
          then:
            - cross-python_${{ target_platform }}
            - python
      host:
        - if: cuda_compiler_version != "None"
          then:
            - cuda-version ==${{ cuda_compiler_version }}
            - cuda-toolkit
        - llvmdev ${{ llvm_version }}.*
        - hatch-fancy-pypi-readme
        - nanobind >=2.6.0
        - pip
        - python
        - scikit-build-core
        - typing_extensions
      run:
        - ${{ pin_compatible("python") }}
        - if: cuda_compiler_version != "None"
          then: cuda-cudart
        - if: osx
          then: libcxx
        - if: linux
          then:
            - libgcc
            - libstdcxx
        - libllvm${{ llvm_version }}
        - python
        - python_abi * *_cp${{ python | version_to_buildstring }}
        - typing_extensions
    tests:
      - python:
          imports:
            - drjit
      - requirements:
          run:
            - pip
            - python
        script:
          - pip check

about:
  homepage: https://github.com/mitsuba-renderer/drjit
  repository: https://github.com/mitsuba-renderer/drjit
  summary: Dr.Jit — A Just-In-Time-Compiler for Differentiable Rendering
  description: |
    Dr.Jit is a just-in-time (JIT) compiler for ordinary and differentiable computation. It was
    originally created as the numerical foundation of Mitsuba 3, a differentiable Monte Carlo
    renderer. However, Dr.Jit is a general-purpose tool that can also help with various other
    types of embarrassingly parallel computation.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jeongseok-meta
